spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sso_db
    username: admin
    password: admin
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "SSO-Hikari-CP"
      register-mbeans: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/database/changelog/changelog-master.xml

frontend:
  base-url: http://localhost:3000
  login-page: ${frontend.base-url}/auth/login


logging:
  level:
    org.springframework.security: trace